# Generated by Django 2.2 on 2019-04-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YumPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('packages', models.CharField(max_length=2048)),
                ('releasever', models.CharField(max_length=128)),
                ('repo_name', models.CharField(max_length=128)),
            ],
        ),
    ]
